### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [jeremy900425/git-practice#1]
先回答你這題「不知道老師能不能將作業繳交的期限延長至一個禮拜?」 ，答案是不行，要自行管理好時間，如果負荷不來那表示可能選太多學分了？可以考慮退選這門課，這門課是選修，不是必修，沒有一定要上。

上課時特別先分享我之前的教學經驗，我所帶的學員是什麼樣貌，就是想讓你們知道，這世界上有人是這樣在努力著，如果作為 0 基礎的人都能努力做到、努力跟上進度，相關科系的你們，我相信你們更可以，何況給你們的作業份量已經遠少於我之前的學員了。

下次上課時，我也會分享作業設計的目標，以及為什麼不能遲交跟晚一週交，你可以不認同，那我真的就是建議去選其他課吧，我不是典型的大學老師，我的目標是訓練出合格的軟體工程師，從硬技術到軟技能都可以有競爭力的軟體工程師，上課時也說了，我很機車，但你們可以不接受。

-----

其他作業部分，希望你可以透過這門課對技術有更深層的認識與觀察，例如

> Commit 是一個儲存點，記錄了檔案在某個時間點的狀態。每次提交（commit）後，Git 都會記住當前的檔案和目錄狀態，方便未來查詢。

那 commit 到底是怎麼紀錄某個時間點的狀態？

在觀察資料夾變化部分:
> 提交後，會在 .git/objects/ 中看到一些新增的檔案，這些是 Git 用來儲存提交內容的地方。

那具體到底新增了什麼檔案？你有親眼觀察到什麼嗎？有的話可以紀錄出來。而這些變化又各自代表了什麼意義？

試試看練習對技術有更多的「好奇心」！

**Comment by jeremy900425** [comment]
感謝老師用心的回覆，經過這週的課程，我理解了為什麼老師要求在 3～4 天內完成作業。也發現這樣的教學模式非常有趣，我非常喜歡這種課堂討論的方式，不知不覺中進入了「上課的狀態」，會一直專注地想繼續聽下去。

另外，老師提供的其他同學作業讓我意識到，自己無法變得更優秀，原因在於這些同學在每次作業中都非常用心，而我卻抱著得過且過的心態去完成。

因此，我重新寫了一次 git.md 的作業，增加了更多內容、圖片，也新增了關於 blob、tree、commit、branch 和 HEAD 的實驗內容。

**非常感謝老師的用心回覆**

**Comment by azole** [comment]
宸宇，很開心知道你能理解整個課程設計，也願意重寫作業，我稍後會仔細看過。

想先請教你一件事，不知道你的回覆是否可以讓我匿名分享在社群平台上？你的理解對我來說，是在教學工作上，很大的鼓勵。

**Comment by jeremy900425** [comment]
沒問題的～

真的很感謝老師 即使班上超過40甚至更多人，也都很認真的對待每一位同學並且給出很多建議以及反饋，同時也讓這門課的變的是如此的無價！

**Comment by azole** [comment]
我看過你新版的 git.md 了，進步非常多，有很多你「個人特有」的紀錄，你要知道，這個就是只有你個人才有的紀錄，這才是最重要且珍貴的，這學期都繼續保持這個水準，不，我覺得你應該可以持續進步，會愈做愈好，我很期待你之後的表現。

一個小提醒，你可以查一下這個檔案是什麼，以及他應該被 push 上 github 嗎？如果不應該的話，可以怎麼做？
<img width="122" alt="image" src="https://github.com/user-attachments/assets/7997f6c8-782b-485e-a559-7f3c35a0df84">

week-02 的作業，我會等明天晚上期限到後，統一看。

**Comment by jeremy900425** [comment]
感謝老師的肯定 我會進我所能的用心參與這門課的

另外，我也將 .DS_Store 是什麼的新增在week02中的md裡面了

**Comment by azole** [comment]
收到，那這個 issue 如果沒有要再繼續討論的地方，就可以先 close 嚕！
